### ISSUE TITLE
Support unsetting environment variables globally

### ISSUE THREAD

**Issue by automaticgiant** [rliebz/tusk#10]
and can't decide if environment unsetting should be a feature.
because sh support, can prepend `unset {no,NO,all,ALL,http,HTTP}{s,}_{proxy,PROXY}; ` to command, which is cool because it's terse, but uncool because it's not consistent or as orthogonal as the existing environment function (can't use globally).

**Comment by rliebz** [comment]
This I think is part of a bigger design issue that needs addressing, which is how changes specific to that shell can persist between different commands, and whether they should do that by default (probably not).

For example, what if someone wanted to export environment variables in the same manner, which in your case is certainly more elegant than what Tusk provides. But it isn't limited to environment variables—things like `set -e` or defining new shell functions fall into the same category. I don't think a syntax specific to unsetting is necessarily the solution. I'll have to think on this one, although I'm certainly open to ideas.

For now, for simple workflows, you can always use multi-line shell commands:
```yaml
tasks:
  foo:
    run: |
      unset {no,NO,all,ALL,http,HTTP}{s,}_{proxy,PROXY};
      echo "Proxy settings cleared!"
      curl ...
```

**Comment by rliebz** [comment]
Alright, after some thought I do actually think the resolution to this is not some grander change in how the shell's environment is persisted, but rather a general change with how Tusk handles environment variables. 

Right now, the `export` clause in `option` has a number of design issues:
- Like you mentioned, there is no logical syntax for unsetting an environment variable
- Currently, options are not evaluated unless required by interpolation or a `when` clause, meaning there's a chance you aren't actually exporting what you think you are. This is a bug
- To _only_ export an environment variable and not use a command-line flag, you'd have to declare an option and mark it as `private`, which is a lot of overhead
- Evaluating an `option` can affect shell execution for any task or sub-task, which seems like a bad design overall

I think the solution is to deprecate the existing syntax and move environment variable handling to the `run` clause, which would look something like this:
```yaml
tasks:
  example:
    options:
      foo:
        default: foovalue
    run:
      setenv: # maybe `set-environment`, `set_environment`, `environ`, etc.
        VAR_ONE: ${foo}
        VAR_TWO: bar
        VAR_THREE: ''
        VAR_FOUR: ~
```

After running the above, `VAR_ONE` is `foovalue` (or the value of the flag passed), `VAR_TWO` is `bar`, `VAR_THREE` is set to an empty string, and `VAR_FOUR` is explicitly unset from whatever value it used to be. This has the advantage of exposing the fact that changing environment variables is an action, not a setting, and therefore allowing it to be done at any point during task execution or even conditionally.

I don't think I'm sold on the idea of supporting brace expansion, but for your use case, you'd still be able to do this:
```yaml
tasks:
  unset-proxy:
    run:
      setenv:
        no_proxy: ~
        all_proxy: ~
        http_proxy: ~
        https_proxy: ~
        # ...
  my-task:
    run:
      - task: unset-proxy
      - command: # ...
```
