### ISSUE TITLE
Require flags to be passed explicitly to sub-tasks

### ISSUE THREAD

**Issue by rliebz** [rliebz/tusk#11]
Currently, the behavior is that flags available to a sub-task will be automatically propagated to any task that calls it. The desired future behavior is that sub-tasks will use their defaults unless explicitly overridden.

The syntax would look something like this:

```yaml
tasks:
  pre-task:
    options:
      foo:
        default: foodefault
  main-task:
    run:
      task:
        name: pre-task
        options:
          foo: override
```

For any task `main-task` where its sub-task has an option `foo`:
- When calling `tusk main-task`, the `--foo` flag would not be visible unless explicitly defined in `main-task` as an option.
- If `foo` is not overridden in the configuration, it will use the default value for the sub-task.
- Interpolation will happen independently for `main-task` and its sub-task. This means they can both define an option `foo` that can have different defaults and evaluate to different values at run time.

The config syntax can be backward compatible if `name` is the implicit default for a `task` `run` action. The following two snippets would then be equivalent:

```yaml
# Option 1
task: pre-task

# Option 2
task:
  name: pre-task
```

This would also allow an easy extension of sub-task configuration, should other options become available. Below are some theoretical examples:

```yaml
run:
  task:
    name: pre-task
    options:
      foo: foovalue
    args:
      - argvalue
    directory: path/to/execute
```

Because this removes the automatic exposing of sub-task options, it will be a breaking change for the CLI.
