### ISSUE TITLE
Allow changing working directory as configuration

### ISSUE THREAD

**Issue by rliebz** [rliebz/tusk#13]
This is a bit of a design challenge due to the number of places that the working directory can be defined, and the ambiguity of which definition should take precedent and how it should propagate to nested members.

Here is my current proposal, in order from lowest to highest priority to determine directory (higher numbers override lower numbers):

1. At the root of the config file, which would change the default working directory for all commands.
2. By command-line, as `tusk -d` or `tusk --directory`, which would have the same properties as and override 1.
3. At the task level, which would change the working directory for all task options and commands, but not global options or sub-tasks.
4. At the sub-task level, to override the default directory for the sub-task which is being run.
5. At the command level, only for that specific command.

Alternatively, it is possible to do one of the following combinations of the above for a slightly less complicated spec:
- 1
- 1, 2
- 1, 2, 5
- 1, 3
- 1, 3, 4
- 1, 5
- 5

All relative paths will be relative to `tusk.yml` and not the working directory.

The YAML syntax for those scenarios would look like this:

```yaml
# 1
directory: path/to/foo

options:
  global-opt:
    default:
      command:
        # Could also be `text`, `exec`, `script`, etc.
        string: pwd
        # 5
        directory: path/to/foo

tasks:
  sub-task:
    # 3
    directory: path/to/foo
  main-task:
    directory: path/to/foo
    run:
      task:
        name: sub-task
        # 4
        directory: path/to/foo
```

And from the CLI:

```bash
# 2
tusk --directory path/to/foo main-task
```
