### ISSUE TITLE
Overwrite Default Help Message

### ISSUE THREAD

**Issue by discreet** [rliebz/tusk#24]
This is more of a question than an issue. I'm working on using tusk to act as a cli wrapper for an Ansible playbook I use. I am creating an alias so the command name better fits the project. The downside is that when the help menu is shown I still see

```
tusk - a task runner built with simplicity in mind

Usage:
   tusk [global options] <task> [task options]
```

Is it possible to overwrite this message?

**Comment by rliebz** [comment]
It's not currently possible to overwrite this message, but it should be an easy add. 

I'm leaning toward this:

```yaml
name: some-alias
usage: this description is for a custom aliased tool

tasks:
  ...
```

And it would produce documentation like this:
```
some-alias - this description is for a custom aliased tool

Usage:
  some-alias [global options] <task> [task options]

Tasks:
  ...
```
