### ISSUE TITLE
Get PID of spawned process

### ISSUE THREAD

**Issue by rhd** [rliebz/tusk#25]
Hi,

How do I spawn a process and pass the PID back so I can kill it later?

```
  sleep:
    run:
    - command:
      - sleep 5 & export FOO=$! && echo $FOO
      - echo $FOO
```

`FOO` gets printed in the first line, but not the 2nd line with `echo`.

Thoughts?

**Comment by rhd** [comment]
I guess this works...

```
      - sleep 5 & echo -n "$!" > sleep.pid
      - kill `cat sleep.pid`
```

Any other way to get the PID into a variable?

**Comment by rliebz** [comment]
By passing a list of commands to `command`, you'll actually get a separate shell process for each item in the list. For the example above, you would be able to access the environment variable by using a multi-line string instead of a list:

```yaml
tasks:
  sleep:
    run:
    - command: |
        sleep 5 & export FOO=$! && echo $FOO
        echo $FOO
```

Be aware here that with multi-line strings, the command is run like a script in that it will continue to execute after non-zero return codes unless you explicitly exit or do something like `set -e`.
