### ISSUE TITLE
Add a config which can be set to prompt before execution of a task

### ISSUE THREAD

**Issue by khimaros** [rliebz/tusk#43]
Something like:

```
tasks:
  clean:
    usage: Remove all temporary files
    run: rm *.o
    prompt: true
```

**Comment by rliebz** [comment]
Thanks for opening an issue!

For reasons [I described here](https://github.com/rliebz/tusk/issues/42#issuecomment-452162633), I don't think it's possible at the task level to get a summary of commands that are going to be run. That leaves us with two options for how to implement this:

1. Prompt before running a task, using only the task usage/description. 

  For the following `tusk.yml` (same as above with an added description for proof-of-concept):
  ```yaml
  tasks:
    clean:
      usage: Remove all temporary files
      description: |
        Removes all files in the project's root directory that end with the `.o` extension.
      run: rm *.o
      prompt: true
  ```

The best tusk can definitively provide would be something like this:
```
$ tusk clean
Are you sure you want to run the following task?

  clean - Remove all temporary files

  Removes all files in the project's root directory that end with the `.o` extension.

[ (c)ontinue, (s)kip, e(x)it ] 
```

2. Offer confirmation at the run-clause level rather than the task-level. 

This moves `prompt` in a level of indentation, but lets us avoid prompting the user until after we're certain what we're going to be running:

```yaml
tasks:
  clean:
    usage: Remove all temporary files
    run: 
      command: rm *.o
      prompt: true
```

In this case we can print a shell command preview (like your example), task preview (like for option 1),  or any other run-clause specific previous based on what exactly it is we're running. 

@khimaros — I'm curious if you have any thoughts or other details about your use case that might help inform what the best design is here.

**Comment by smyrman** [comment]
Another suggestion could be to prompt for the value of _options_ (at the start of the task, including sub-tasks). Perhaps adding a global `--no-interactive` flag to disable all prompts and error if required flags are missing. Alternatively do it the other way around and require an `--interactive` flag; which ever makes more sense.

An idea could be to add a new options/args field `prompt` that, if set, triggers an option/arg value to be prompted for if not explicitly set or passed to a task. A promptType could additionally be added to allow for advanced usage such as supplying passwords.

Example for the confirm case, which this issue is about:

```yaml
tasks:
  foo:
    options:
      confirm:
        type: bool
        usage: "confirm operation"
        prompt: "Are you sure you want to do foo?"
        required: true # can also be false of course
```
Will error (since `confirm` is required):
```
sh $ tusk --no-interactive foo
```
Will succeed:
```
sh $ tusk  --no-interactive  foo --confirm
```
Will prompt:
```
sh $ tusk foo
foo > Are you sure you want to do foo? [y/n]
```

An implementation could e.g. rely on https://github.com/AlecAivazis/survey.

If combined with #50, one could even allow multiple-select for the varargs argument(s) of a task and/or sub-task.
