### ISSUE TITLE
Provide help documentation for argument usage

### ISSUE THREAD

**Issue by rliebz** [rliebz/tusk#44]
Related: #12

While positional arguments are supported, the command-line help documentation is extremely minimal.

Given the following config:
```yaml
tasks:
  greet:
    args:
      name:
        usage: The person to greet
    run: echo "Hello, ${name}!"
```

We see the following documentation:
```text
$ tusk greet --help
tusk greet

Usage:
    tusk greet <name>
```

Documentation should include the argument usage in a format similar to how flags are currently printed. For example:

```text
$ tusk greet --help
tusk greet

Usage:
    tusk greet <name>

Arguments:
    name  The person to greet
