### ISSUE TITLE
Arguments/Parameters

### ISSUE THREAD

**Issue by Murilo2508** [rliebz/tusk#50]
Is there a way to get any parameter passed to a task?
I have this task: 
```
  app: 
    usage: access app container and execute commands 
    args: 
      command: 
        usage: the command that app will run 
    run: docker-compose exec app ${command} 
```
And when I try to rund this task with `tusk app php artisan` I got this error `Error task "app" requires exactly 1 args, got 2`.
I have managed to fix this problem with `tusk app "php artisan"`, but I want to know if there is a way like in shell script with $@ to get all parameters?

**Comment by rliebz** [comment]
Hey @Murilo2508, thanks for opening an issue.

There currently is not any way to get the behavior you're looking for, other than enclosing a list of arguments in quotes, like you're doing now.

When I'd thought about the design for a feature like this, it usually would work like shell aliases or `npm run`, where the tusk command would indicate a prefix and all remaining arguments would be passed through. The syntax looked something like this:

```yaml
tasks:
  app: 
    usage: access app container and execute commands
    # Some flag to indicate arguments are passed through.
    # Exact syntax up in the air--could be `args: passthrough`, etc.
    pass-through: true
    run: docker-compose exec app
```

That said, I kind of like the more explicit syntax you have in that example. I could see something like a `vararg: true` field available on the last argument, which would signal tusk to take an arbitrary number of strings to substitute in. It would also allow mixing fixed args and flags with variable args, which the pass-through style would not. 

This is definitely something I'm open to adding, but it may take some time playing around to get a design I'm happy with. The reason relates to discoverability—right now, tusk is able to offer comprehensive documentation, tab-completion, and validation for command-line options/args passed to a task. Passing things through to an underlying command means trading those benefits for flexibility, which is doable, but might take some thinking.
