### ISSUE TITLE
variable containing relative path to tusk

### ISSUE THREAD

**Issue by cuotos** [rliebz/tusk#59]
I have a simple task that writes out to a file, the name of which is passed as an option.

But the outputted file is relative to the tusk.yaml file not the location where the tusk command was run. 

Is there a simple way (that i've missed) to automatically provide the relative path from tusk.yaml to where I am when I run the command?

```
command: echo "something" > ${relativePath}/${outputfile}
```

**Comment by rliebz** [comment]
The easiest way to do this is to rely on the fact that shells have the `$PWD` environment variable set for you already. While the environment variable will change when the actual command is being run, the initial value can be captured as an option:

```yaml
tasks:
  my-task:
    options:
      dir:
        environment: PWD
    run:
      - pwd
      - echo $PWD
      - echo ${dir}
```

Which, in a project, will yield something like this:
```
$ tusk my-task
my-task $ pwd
/Users/rliebz/my-proj
my-task $ echo /Users/rliebz/my-proj/child
/Users/rliebz/my-proj/child
```

Because interpolation of tusk options happens before the command is actually run, you get the environment variable that reflects your actual working directory.
