### ISSUE TITLE
Support marking options as secret to avoid printing by CLI

### ISSUE THREAD

**Issue by rliebz** [rliebz/tusk#61]
**Is your feature request related to a problem? Please describe.**

While it is currently possible to avoid printing shell commands through use of [the print clause](https://rliebz.github.io/tusk/spec/#print), it would be nice to flag that at the variable level so it happens automatically.

**Describe the solution you'd like**

There could be a `secret` flag attached to options that would cause it to get masked when printed, either as `${varname}` without interpolation or something like `*****`.

```yaml
tasks:
  foo:
    options:
      my-password:
        usage: Secret to pass to an application
        secret: true
    run:
      command: cmd --password ${my-password}
```

**Additional context**

See https://github.com/rliebz/tusk/issues/54#issuecomment-524227781
