### ISSUE TITLE
Support of variables and foreach

### ISSUE THREAD

**Issue by Hobart2967** [rliebz/tusk#63]
**Is your feature request related to a problem? Please describe.**
Id like to see an option to set variables like real option values as shared variable.

Example:

```
vars:
  enabled-environments:
    - dev
    - prod
    - all

tasks:
  build:
    options:
      environment:
        values: ${enabled-environments}
    run:
      - when: 
            equal: { environment: 'all' }
         task: build-all
      - when:
          not-equal: { environment: 'all' }
        run:
           yarn build:${environment}
  build-all:
    run:
      - foreach:
           list: ${enabled-environments}
           as: current-environment
           task: # or run:
              name: build
              options:
                 environment: ${current-environment}
 ```
      

**Describe the solution you'd like**
This makes it easier to build a cli with an include all or specific option.
