### ISSUE TITLE
Support for conditional requirement of options

### ISSUE THREAD

**Issue by Hobart2967** [rliebz/tusk#65]
**Is your feature request related to a problem? Please describe.**
Depending on the options and args given I'd like to require additional options. For example, I have a build task that requires an option "name" in some cases, but not in all.

The structure for "when" in tasks is great already and looks suitable to the requiring of options, too.

**Describe the solution you'd like**
```
# ...
  build:
    usage: Builds a part of this product (Angular app, SSR Host, Font, Api Libraries)
    args:
      artifact:
        usage: "Type of artifact to build"
        values:
          - browser
          - api
    options:
      name:
        usage: Name of the target to build
        required:
          when:
            - { artifact: 'api' }
# ....
```
