### ISSUE TITLE
support for user-prompt

### ISSUE THREAD

**Issue by Hobart2967** [rliebz/tusk#66]
**Is your feature request related to a problem? Please describe.**
I'd like to see an option where a user is asked for an option in order to make the cli interactively.

**Describe the solution you'd like**
```
tasks: 
  setup:
    run: 
      - prompt:
           msg: "Please enter an api key:"
           type: string
           default: "foobar"
           var: api-key
      - command: |
           echo "export API_KEY=\'"${apiKey}\"" >>> ~/.bashrc
      - prompt: 
           msg: "Do you want to delete /home?"
           type: boolean
           default: true
           var: delete-home
       - when:
            equal: { delete-home: true }
            - command: rm -rf /home
```

Result: 
```
user@machine # tusk
Please enter an api key [foobar]: barfoo
Do you want to delete /home? [Y/n]: n
```
