### ISSUE TITLE
Default values from subtask output

### ISSUE THREAD

**Issue by airtonix** [rliebz/tusk#71]
**Is your feature request related to a problem? Please describe.**

aws login

- our aws cli is in a docker container
- windows machines require win-bash, but this causes problems for running tusk as `command` parameter in options default.

```

  aws:
    args:
      command:
        usage: command to pass to aws cli
    run:
      - command:
          - >-
            docker run --rm -it
            -w /app
            -v ${HOME}${USERPROFILE}/.aws/:/root/.aws/
            -v ${PWD}:/app/
            nexus.morgoth.studylink.com:5000/awscli
            ${command}

  aws:ecr-get-login:
    run:
      task:
        name: aws
        args: >-
          aws ecr get-login-password --region ap-southeast-2

  aws:ecr-login:
    options:
      login:
        private: true
        default:
          command: tusk aws:ecr-get-login
    run:
      - echo ${login} | docker login --username AWS --password-stdin <id>.dkr.ecr.<region>.amazonaws.com
```

**Describe the solution you'd like**

```
  aws:ecr-login:
    options:
      login:
        private: true
        default:
          task:
            name: aws:ecr-get-login
    run:
      - echo ${login} | docker login --username AWS --password-stdin <id>.dkr.ecr.<region>.amazonaws.com
```

**Additional context**
