### ISSUE TITLE
Question: when variable set/unset

### ISSUE THREAD

**Issue by airtonix** [rliebz/tusk#78]
related to #15, but about `options` for a specific task

Currently we can do things if an environment variable is not set:
```yml
tasks:
  foo:
    run:
      when:
        environment:
          BAR: ~
      command: do-thing-when-no-bar
```

But how can we do the same for options on a task that are not set?
```yml
tasks:
  foo:
    options:
      bar:
        usage: visit them all
    run:
      when:
        option:
          bar: ~
      command: do-thing-when-no-bar
```

**Comment by rliebz** [comment]
Is checking for the default value sufficient here?

```yaml
tasks:
  foo:
    options:
      bar:
        usage: visit them all
    run:
      when:
        equal: {bar: ''}
      command: do-thing-when-no-bar
```

That would run in the following scenarios:

```bash
tusk foo               # yes
tusk foo --bar ''      # yes
tusk foo --bar 'value' # no
```

If you do need to handle the second case differently, there currently isn't a way, but I haven't personally run into that use case before.
