### ISSUE TITLE
Add support for sub commands

### ISSUE THREAD

**Issue by tstmrk** [rliebz/tusk#80]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I would like to have a feature where I can add a subcommand to a task, like you see with kubectl or gcloud. 

So that I can do the following
`
customctl command subcommand --argument value
`

**Additional context**
Just like

`
kubectl config get-contexts
`

If there is any other way I can do this, please let me know :-)

**Comment by airtonix** [comment]
if it's just a matter of taste that you want the subcommands separated by spaces, then I would suggest following this pattern commonly used in the npm/yarn world: 

```yml

tasks:

  greet:
    usage: Say hello to someone
    options:
      name:
        usage: A person to say "Hello" to
        default: World
    run: echo "Hello, ${name}!"

 greet:me:
    run:
      task:
        name: greet
        options: { name: 'me' }

 greet:you:
    run:
      task:
        name: greet
        options: { name: 'you' }
```

`tusk greet:me`
