### ISSUE TITLE
When "OR" equals query

### ISSUE THREAD

**Issue by cuotos** [rliebz/tusk#81]
my task has a list of options, I want to run the task if either of two are provided. It doesn't appear to be possible to add multiple "equal" checks to a single When statement. 

The documented example covers "if `os` AND/OR an option is `equal`, but not a case of multiple `equal`s.

Is these another way this can be done?

```
    options:
      check:
        default: all
        values: 
          - all
          - option1
          - option2
    run: 
      - when:
          - equal: {check: all}
             equal: {check: option1} # cannot unmarshal if this exists.
        command: echo hi  
```

**Comment by cuotos** [comment]
i solved by own issue with

```
      - when:
          - equal: 
              <option name>: 
                - all
                - option1
        command: echo hi
```

ill try and create a PR to clarify in documentation
