### ISSUE TITLE
evaluate environment variables in shared options

### ISSUE THREAD

**Issue by robinbryce** [rliebz/tusk#83]
**Is your feature request related to a problem? Please describe.**

For in house tools which we wrap using tusk, we would like to select different configuration profiles (and other things) by default based on the USERNAME or LOGNAME of the current user. And yet allow that choice to be overriden. We would ideally like other environment variables to be possible also.

**Describe the solution you'd like**

Environment variables referenced in the shared options would be evaluated in the default values. It is ok if this is done 'lazily', when the shared options are referenced by a task.

```
options:
  configname:
    usage: "selected configuration"
    short: "c"
    default: "dev-${USER}"

```

**Additional context**
The ability to evaluate shell expressions would also be welcome.

**Comment by rliebz** [comment]
Thanks for opening an issue!

There are subtle reasons why tusk can't directly evaluate environment variables in that context. The good news is there is a way to do this currently using the `command` clause, which is a shell expression:

```yaml
options:
  configname:
    usage: "selected configuration"
    short: "c"
    default: 
      command: echo "dev-$USER"
```
