### ISSUE TITLE
Import arbitrarty YAML/JSON

### ISSUE THREAD

**Issue by smyrman** [rliebz/tusk#85]
**Is your feature request related to a problem? Please describe.**

Sometimes it would be nice to be able to _import_ arbitrary data from other YAML (or JSON) files, and use values from these files without having to duplicate configuration.

One concrete example is config files generated by [appctl](https://cloud.google.com/kubernetes-engine/docs/how-to/add-on/application-delivery) that look something like this:

```yaml
cluster_name: NAME
project: PROJECT
compute:  # choose "region" or "zone"
   region: REGION
namespace: NAMESPACE
no_pr_approval_required: false
```
It would be nice to be able to _extrat_ and work with these variables in tusk in one way or another.

**Describe the solution you'd like**

It's not important to me _how_ this works. But here is one possible syntax:

```
imports: # new section imports
   <name>: # name of import
     path: <file> # path to file to import
     expose: # map of values to expose, and what to expose them as.
       <local name/alias>: <dotted path in file>
```

Full example:

```yaml
imports: # new section imports
  delivery-dev: # name of import
    path: delivery/envs/dev.yaml # path to import from
    expose: &delivery-expose # mapping to variables to expose
      cluster: cluster_name
      project: project
      region: compute.region
      namespace: namespace
 delivery-staging: 
    path: delivery/envs/staging.yaml
    expose: *delivery-expose
  delivery-prod:
    path: delivery/envs/prod.yaml
    expose: *delivery-expose
    
tasks:  
  use-context:
    usage: "Switch to the cluster belonging to a particular deployment"

    args:
      env:
        usage: Name of environment
        values:
          - dev
          - staging
          - prod

    run:
      - command: kubectl config use-context gke_${delivery.project}_${delivery.region}_${delivery.cluster}
         with-alias: # another feature to alias variables (not strictly needed for this, just reduce code).
           delivery: "imports.delivery-${env}"
```

The final run line without an "alias" feature:

```yaml

    run:
      - command: kubectl config use-context gke_${delivery-dev.project}_${delivery-dev.region}_${delivery-dev.cluster}
         when:
         - {"equal":  {"env": "dev"}
      - command: kubectl config use-context gke_${delivery-staging.project}_${delivery-staging.region}_${delivery-staging.cluster}
         when:
         - {"equal":  {"env": "staging"}
      - command: kubectl config use-context gke_${delivery-prod.project}_${delivery-prod.region}_${delivery-prod.cluster}
         when:
         - {"equal":  {"env": "prod"}
```

**Additional context**

**Comment by moondev** [comment]
Another solution for this is simply including the yaml as additional  documents in `tusk.yaml` and reading them with a utility like `yq` https://github.com/mikefarah/yq

`tusk` only reads the first document and ignores additional yaml documents inside `tusk.yaml`

note: golang `1.17.x` required for this `tusk.yaml` example 

```yaml
#!/usr/bin/env -S go run github.com/rliebz/tusk@v0.6.2 -f
---
tasks:
  read-one:
    run:
      - go run github.com/mikefarah/yq/v3@latest r tusk.yaml -d1
  read-two:
    run:
      - go run github.com/mikefarah/yq/v3@latest r tusk.yaml -d2 spec

---
document: one

---
spec:
  document:
    two: example
```

```
./tusk.yaml read-one
./tusk.yaml read-two
```
